version: '3.7'

services:
  latest:
    build: .
    image: make-cpu
    container_name: make-cpu
    user: "1000:1000"
    ports:
      - 3389:3389
    environment:
      USER: yamamoto
      PASSWD: yamamoto
    volumes:
      - ./:/home

